include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
    invalid_annotation_target: ignore
  exclude:
    - "bin/cache/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/injector.config.dart"
linter:
  rules:
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    camel_case_types: true
    constant_identifier_names: false
    close_sinks: true
    curly_braces_in_flow_control_structures: true
    empty_constructor_bodies: true
    lines_longer_than_80_chars: false
    prefer_collection_literals: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    slash_for_doc_comments: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    unnecessary_await_in_return: true

    cancel_subscriptions: true
    directives_ordering: true
    empty_statements: true
    prefer_final_fields: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_interpolation_to_compose_strings: true
    prefer_contains: true
    void_checks: true

    # sort_pub_dependencies: true
    prefer_equal_for_default_values: true
    prefer_if_null_operators: true
    prefer_is_not_empty: true
    prefer_is_empty: true
    prefer_null_aware_operators: true
    require_trailing_commas: true
    sized_box_shrink_expand: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_late: true
    use_if_null_to_convert_nulls_to_bools: true
    use_colored_box: true
    use_decorated_box: true
    use_named_constants: true
    use_rethrow_when_possible: true
    use_super_parameters: false
    avoid_web_libraries_in_flutter: false
